[files]
scriptdir = "code/mads-autoshutdown"
api-token = "api-token.txt"
csrf-token = "csrf-token.txt"
ids = "output.csv"
logfile = "logs.log"

[surf]
URL = "https://gw.live.surfresearchcloud.nl/v1/workspace/workspaces"

